#!/usr/bin/env python3
"""Generate the synthetic OFD fixture used by the test suite.

Run ``python tests/make_sample.py`` to (re)build ``tests/data/sample.ofd``.
Everything here is fake — no real personal data — and uses only the standard
library so the fixture can be regenerated anywhere.

The sample deliberately exercises the features ofd2pdf renders.  Page 1 is a
150 x 100 mm invoice, page 2 is a 120 x 70 mm detail sheet:

* two pages with **different page sizes**, background *and* foreground
  templates, plus a page-local ``<ofd:Res>`` with its own ``DrawParam``,
* text objects with ``DeltaX``, the ``g N v`` repeat form, several ``TextCode``
  children in one object, ``\\XXXX`` escapes, ``HScale``, ``ReadDirection``
  90/180/270, ``CharDirection`` and a vertical run driven by ``DeltaY``,
* stroke-only text, text fill alpha, and a ``cmyk`` colour,
* paths using ``S``/``M``/``L``/``Q``/``B``/``A``/``C``, an ``Even-Odd`` donut,
  dashes, round caps/joins, and a ``DrawParam`` inherited from the layer,
* a ``CompositeObject`` nested inline **and** one referencing a
  ``CompositeGraphicUnit`` resource by ``ResourceID`` (the round seal),
* two ``ImageObject``s (one with an ``ImageObject`` CTM, as real invoices
  write them) and an ``ImageMask`` stencil,
* ``Stamp`` annotations with drawn appearances on both pages,
* document metadata and two embedded attachments.

Layout (page 1, 150 x 100 mm)::

    +--------------------------------------------------+
    | [ band ]  测试发票   OFD TEST               [logo]|
    +----------------------+-----------+--------------+
    | NAME  TEST USER      |           | INVOICE      |
    |          INV000000001 |           |              |
    +----------------------+-----------+--------------+
    | AMOUNT 1234567890 备注 样例文件                   |
    | ￥123   SQUEEZED   [star][donut][curve][dashed][V]|
    | [stamp]     [nested composite]                    |
    | 透明文字  OUTLINE       B2UP                RTL180  |
    +--------------------------------------------------+

Page 2 (120 x 70 mm) is a vertical/rotated text and curve playground.
"""

from __future__ import annotations

import math
import os
import struct
import zlib
import zipfile

OUTPUT = os.path.join(os.path.dirname(__file__), "data", "sample.ofd")

NS = "http://www.ofdspec.org/2016"


# -- tiny PNG encoder -------------------------------------------------------
def _png_chunk(tag: bytes, data: bytes) -> bytes:
    return (
        struct.pack(">I", len(data))
        + tag
        + data
        + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
    )


def _make_png(width: int, height: int, pixel) -> bytes:
    raw = bytearray()
    for y in range(height):
        raw.append(0)  # filter type 0
        for x in range(width):
            raw += bytes(pixel(x, y))
    header = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    return (
        b"\x89PNG\r\n\x1a\n"
        + _png_chunk(b"IHDR", header)
        + _png_chunk(b"IDAT", zlib.compress(bytes(raw), 9))
        + _png_chunk(b"IEND", b"")
    )


def _logo_png() -> bytes:
    size = 32

    def pixel(x: int, y: int):
        edge = x < 2 or y < 2 or x >= size - 2 or y >= size - 2
        if edge:
            return (200, 30, 30)
        if (x // 4 + y // 4) % 2 == 0:
            return (255, 240, 240)
        return (255, 255, 255)

    return _make_png(size, size, pixel)


def _stencil_png() -> bytes:
    """A black five-pointed star on white, painted through ``ImageMask``."""

    size = 24
    cx = cy = (size - 1) / 2.0

    def pixel(x: int, y: int):
        dx, dy = x - cx, y - cy
        radius = math.hypot(dx, dy)
        angle = math.atan2(dy, dx)
        edge = 4.0 + 8.0 * math.cos(5 * angle) * 0.5 + 4.0
        return (0, 0, 0) if radius <= edge else (255, 255, 255)

    return _make_png(size, size, pixel)


# -- OFD XML documents ------------------------------------------------------
OFD_XML = f"""<?xml version="1.0" encoding="UTF-8"?>
<ofd:OFD Version="1.1" DocType="OFD" xmlns:ofd="{NS}">
  <ofd:DocBody>
    <ofd:DocInfo>
      <ofd:DocID>sample-ofd-0001</ofd:DocID>
      <ofd:Title>合成测试发票</ofd:Title>
      <ofd:Author>ofd2pdf test</ofd:Author>
      <ofd:Subject>OFD rendering fixture</ofd:Subject>
      <ofd:Abstract>Synthetic document generated by tests/make_sample.py</ofd:Abstract>
      <ofd:Keywords>ofd,invoice,test</ofd:Keywords>
      <ofd:CreationDate>2026-01-01</ofd:CreationDate>
      <ofd:ModDate>2026-01-02</ofd:ModDate>
      <ofd:Creator>ofd2pdf tests</ofd:Creator>
      <ofd:CreatorVersion>0.3</ofd:CreatorVersion>
    </ofd:DocInfo>
    <ofd:DocRoot>Doc_0/Document.xml</ofd:DocRoot>
  </ofd:DocBody>
</ofd:OFD>
"""

DOCUMENT_XML = f"""<?xml version="1.0" encoding="UTF-8"?>
<ofd:Document xmlns:ofd="{NS}">
  <ofd:CommonData>
    <ofd:MaxUnitID>200</ofd:MaxUnitID>
    <ofd:PageArea><ofd:PhysicalBox>0 0 150 100</ofd:PhysicalBox></ofd:PageArea>
    <ofd:PublicRes>PublicRes.xml</ofd:PublicRes>
    <ofd:DocumentRes>DocumentRes.xml</ofd:DocumentRes>
    <ofd:TemplatePage ID="1" BaseLoc="Tpls/Tpl_0/Content.xml" ZOrder="Background"/>
    <ofd:TemplatePage ID="3" BaseLoc="Tpls/Tpl_1/Content.xml" ZOrder="Foreground"/>
  </ofd:CommonData>
  <ofd:Pages>
    <ofd:Page ID="2" BaseLoc="Pages/Page_0/Content.xml"/>
    <ofd:Page ID="4" BaseLoc="Pages/Page_1/Content.xml"/>
  </ofd:Pages>
  <ofd:Annotations>Annots/Annot_0.xml</ofd:Annotations>
  <ofd:Attachments>Attachs/Attachments.xml</ofd:Attachments>
</ofd:Document>
"""

PUBLIC_RES_XML = f"""<?xml version="1.0" encoding="UTF-8"?>
<ofd:Res xmlns:ofd="{NS}" BaseLoc="Res">
  <ofd:DrawParams>
    <ofd:DrawParam ID="1" LineWidth="0.3"><ofd:StrokeColor Value="60 60 60"/></ofd:DrawParam>
    <ofd:DrawParam ID="2"><ofd:FillColor Value="240 240 245"/></ofd:DrawParam>
    <ofd:DrawParam ID="3" LineWidth="0.5" Cap="Round" Join="Round">
      <ofd:StrokeColor Value="0 90 160"/>
    </ofd:DrawParam>
    <ofd:DrawParam ID="4" LineWidth="0.4">
      <ofd:StrokeColor Value="200 30 30"/>
      <ofd:DashPattern Offset="0" Array="1.2 0.8"/>
    </ofd:DrawParam>
    <ofd:DrawParam ID="5" LineWidth="0.2">
      <ofd:StrokeColor Value="90 90 90" Alpha="128"/>
    </ofd:DrawParam>
  </ofd:DrawParams>
  <ofd:Fonts>
    <ofd:Font ID="5" FontName="宋体" FamilyName="宋体"/>
    <ofd:Font ID="7" FontName="Courier New"/>
    <ofd:Font ID="8" FontName="黑体" FamilyName="黑体" Bold="true"/>
    <ofd:Font ID="11" FontName="仿宋" FamilyName="仿宋" Serif="true"/>
  </ofd:Fonts>
</ofd:Res>
"""

# The round seal lives in a resource and is referenced with ResourceID, the way
# railway e-invoices reference their 发票监制章.
DOCUMENT_RES_XML = f"""<?xml version="1.0" encoding="UTF-8"?>
<ofd:Res xmlns:ofd="{NS}" BaseLoc="Res">
  <ofd:MultiMedias>
    <ofd:MultiMedia ID="9" Type="Image" Format="PNG">
      <ofd:MediaFile>logo.png</ofd:MediaFile>
    </ofd:MultiMedia>
    <ofd:MultiMedia ID="10" Type="Image" Format="PNG">
      <ofd:MediaFile>stencil.png</ofd:MediaFile>
    </ofd:MultiMedia>
  </ofd:MultiMedias>
  <ofd:CompositeGraphicUnits>
    <ofd:CompositeGraphicUnit ID="50" Width="30" Height="30">
      <ofd:Content ID="51" Type="Body">
        <ofd:PageBlock ID="52">
          <ofd:PathObject ID="53" Boundary="0 0 30 30" LineWidth="0.6" Fill="false" Stroke="true">
            <ofd:StrokeColor Value="200 30 30"/>
            <ofd:AbbreviatedData>M 15 1.5 A 13.5 13.5 0 1 0 15 28.5 A 13.5 13.5 0 1 0 15 1.5 C</ofd:AbbreviatedData>
          </ofd:PathObject>
          <ofd:PathObject ID="54" Boundary="0 0 30 30" Fill="false" Stroke="true">
            <ofd:StrokeColor Value="200 30 30"/>
            <ofd:AbbreviatedData>M 6 15 A 9 9 0 1 1 24 15 A 9 9 0 1 1 6 15 C</ofd:AbbreviatedData>
          </ofd:PathObject>
          <ofd:TextObject ID="55" Boundary="3 13 24 6" Font="5" Size="4">
            <ofd:FillColor Value="200 30 30"/>
            <ofd:TextCode X="0" Y="4" DeltaX="4 4 4 4">样例印章</ofd:TextCode>
          </ofd:TextObject>
        </ofd:PageBlock>
      </ofd:Content>
    </ofd:CompositeGraphicUnit>
  </ofd:CompositeGraphicUnits>
</ofd:Res>
"""

TEMPLATE_BACK_XML = f"""<?xml version="1.0" encoding="UTF-8"?>
<ofd:Page xmlns:ofd="{NS}">
  <ofd:Content>
    <ofd:Layer ID="10" DrawParam="2">
      <ofd:PathObject ID="11" Boundary="10 4 130 10" Fill="true" Stroke="false">
        <ofd:AbbreviatedData>M 0 0 L 130 0 L 130 10 L 0 10 C</ofd:AbbreviatedData>
      </ofd:PathObject>
    </ofd:Layer>
    <ofd:Layer ID="12" DrawParam="1">
      <ofd:PathObject ID="13" Boundary="10 20 130 0.4">
        <ofd:AbbreviatedData>M 0 0.2 L 130 0.2</ofd:AbbreviatedData>
      </ofd:PathObject>
      <ofd:PathObject ID="14" Boundary="10 46 130 0.4">
        <ofd:AbbreviatedData>M 0 0.2 L 130 0.2</ofd:AbbreviatedData>
      </ofd:PathObject>
      <ofd:PathObject ID="15" Boundary="10 76 130 0.4">
        <ofd:AbbreviatedData>M 0 0.2 L 130 0.2</ofd:AbbreviatedData>
      </ofd:PathObject>
      <ofd:PathObject ID="16" Boundary="52 20 0.4 56">
        <ofd:AbbreviatedData>M 0.2 0 L 0.2 56</ofd:AbbreviatedData>
      </ofd:PathObject>
      <ofd:PathObject ID="17" Boundary="96 20 0.4 56">
        <ofd:AbbreviatedData>M 0.2 0 L 0.2 56</ofd:AbbreviatedData>
      </ofd:PathObject>
    </ofd:Layer>
  </ofd:Content>
</ofd:Page>
"""

TEMPLATE_FRONT_XML = f"""<?xml version="1.0" encoding="UTF-8"?>
<ofd:Page xmlns:ofd="{NS}">
  <ofd:Content>
    <ofd:Layer ID="14" DrawParam="4">
      <ofd:PathObject ID="15" Boundary="10 92 130 0.4" Fill="false" Stroke="true">
        <ofd:AbbreviatedData>M 0 0.2 L 130 0.2</ofd:AbbreviatedData>
      </ofd:PathObject>
    </ofd:Layer>
  </ofd:Content>
</ofd:Page>
"""

ANNOTS_INDEX_XML = f"""<?xml version="1.0" encoding="UTF-8"?>
<ofd:Annotations xmlns:ofd="{NS}">
  <ofd:Page PageID="2">
    <ofd:FileLoc>Content_0.xml</ofd:FileLoc>
  </ofd:Page>
  <ofd:Page PageID="4">
    <ofd:FileLoc>Content_1.xml</ofd:FileLoc>
  </ofd:Page>
</ofd:Annotations>
"""

ANNOTS_PAGE0_XML = f"""<?xml version="1.0" encoding="UTF-8"?>
<ofd:Page xmlns:ofd="{NS}">
  <ofd:Annot ID="200" Type="Stamp" Subtype="Stamp" Creator="ofd2pdf tests">
    <ofd:Appearance Boundary="14 68 24 24" Format="Ofd" Subtype="Stamp">
      <ofd:PageBlock>
        <ofd:PathObject ID="201" Boundary="0 0 24 24" LineWidth="0.5" Fill="false" Stroke="true">
          <ofd:StrokeColor Value="20 120 90"/>
          <ofd:AbbreviatedData>M 1 1 L 23 1 L 23 23 L 1 23 C</ofd:AbbreviatedData>
        </ofd:PathObject>
        <ofd:TextObject ID="202" Boundary="2 10 20 5" Font="5" Size="4">
          <ofd:FillColor Value="20 120 90"/>
          <ofd:TextCode X="0" Y="4" DeltaX="4 4 4 4">已认证</ofd:TextCode>
        </ofd:TextObject>
      </ofd:PageBlock>
    </ofd:Appearance>
  </ofd:Annot>
</ofd:Page>
"""

ANNOTS_PAGE1_XML = f"""<?xml version="1.0" encoding="UTF-8"?>
<ofd:Page xmlns:ofd="{NS}">
  <ofd:Annot ID="210" Type="Stamp" Subtype="Stamp">
    <ofd:Appearance Boundary="56 40 26 12" Format="Ofd" Subtype="Stamp">
      <ofd:PageBlock>
        <ofd:PathObject ID="211" Boundary="0 0 26 12" LineWidth="0.4" Fill="true" Stroke="true">
          <ofd:FillColor Value="250 235 200" Alpha="200"/>
          <ofd:StrokeColor Value="150 100 20"/>
          <ofd:AbbreviatedData>M 0.6 0.6 L 25.4 0.6 L 25.4 11.4 L 0.6 11.4 C</ofd:AbbreviatedData>
        </ofd:PathObject>
        <ofd:TextObject ID="212" Boundary="2 3 22 6" Font="5" Size="4">
          <ofd:FillColor Value="120 70 10"/>
          <ofd:TextCode X="0" Y="4" DeltaX="4 4 4">附注</ofd:TextCode>
        </ofd:TextObject>
      </ofd:PageBlock>
    </ofd:Appearance>
  </ofd:Annot>
</ofd:Page>
"""

ATTACHMENTS_XML = f"""<?xml version="1.0" encoding="UTF-8"?>
<ofd:Attachments xmlns:ofd="{NS}">
  <ofd:Attachment ID="300" Name="readme.txt" Format="txt">
    <ofd:FileLoc>readme.txt</ofd:FileLoc>
  </ofd:Attachment>
  <ofd:Attachment ID="301" Name="data.csv" Format="csv">
    <ofd:FileLoc>data.csv</ofd:FileLoc>
  </ofd:Attachment>
</ofd:Attachments>
"""


def _text(oid, text, x, y, size, font, deltas, boundary, extra="", codes=None):
    if codes is None:
        delta = " ".join(str(d) for d in deltas)
        codes = (
            f'        <ofd:TextCode X="{x}" Y="{y}" DeltaX="{delta}">{text}</ofd:TextCode>\n'
        )
    return (
        f'      <ofd:TextObject ID="{oid}" Boundary="{boundary}" Font="{font}" '
        f'Size="{size}"{extra}>\n'
        f'        <ofd:FillColor Value="0 0 0"/>\n'
        f"{codes}"
        f"      </ofd:TextObject>\n"
    )


def _vertical(oid, text, boundary, size, font=5):
    """A stacked CJK run: one TextCode, every glyph one em lower (``DeltaY``).

    *boundary* is the top-left of the run, so the first glyph's baseline sits
    at the boundary origin and the rest march down the page, i.e. the text
    reads top to bottom.
    """
    deltas = " ".join(f"{size:g}" for _ in text)
    return (
        f'      <ofd:TextObject ID="{oid}" Boundary="{boundary}" Font="{font}" '
        f'Size="{size}">\n'
        f'        <ofd:FillColor Value="0 0 0"/>\n'
        f'        <ofd:TextCode X="0" Y="0" DeltaY="{deltas}">{text}</ofd:TextCode>\n'
        f"      </ofd:TextObject>\n"
    )


def page1_xml() -> str:
    parts = [
        # Title: CJK then Latin, with per-glyph advances.
        _text(20, "测试发票", 0, 4.2, 5, 5, [5, 5, 5, 5], "14 8 40 7"),
        _text(21, "OFD TEST", 0, 4.2, 4.5, 7, [2.25] * 8, "44 8 40 7"),
        # Name / invoice row.
        _text(22, "NAME", 0, 3.2, 3.5, 7, [1.75] * 4, "14 26 36 5"),
        _text(23, "TEST USER", 0, 3.2, 3.5, 7, [1.75] * 9, "54 26 40 5"),
        _text(24, "INVOICE", 0, 3.2, 3.5, 7, [1.75] * 7, "98 26 40 5"),
        _text(25, "INV000000001", 0, 3.2, 3.5, 7, [1.75] * 12, "54 36 80 5"),
        # Amount row: a bold face, and a `g N v` repeated advance.
        _text(26, "AMOUNT", 0, 3.2, 3.5, 8, [1.9] * 6, "14 52 36 5"),
        _text(27, "1234567890", 0, 3.2, 4, 7, [], "54 52 40 5",
              codes='        <ofd:TextCode X="0" Y="3.2" DeltaX="g 10 2">1234567890</ofd:TextCode>\n'),
        _text(28, "备注", 0, 3.6, 4, 5, [4, 4], "98 52 20 5"),
        _text(29, "样例文件", 0, 3.6, 4, 5, [4, 4, 4, 4], "120 52 28 5"),
        # \XXXX escapes: fullwidth yen U+FFE5 plus "123".
        _text(30, "\\FFE5\\0031\\0032\\0033", 0, 3.2, 4, 5, [4, 2.2, 2.2, 2.2],
              "14 62 30 5"),
        # A horizontally squeezed run.
        _text(31, "SQUEEZED", 0, 3.2, 3.5, 7, [1.6] * 8, "54 62 40 5",
              extra=' HScale="0.6"'),
        # Filled alpha text in cmyk, plus outlined (stroke only) text.
        _text(32, "透明文字", 0, 3.6, 4, 5, [4, 4, 4, 4], "44 82 30 5",
              codes='        <ofd:FillColor ColorSpace="15" Value="0 0.6 0.8 0" Alpha="140"/>\n'
                    '        <ofd:TextCode X="0" Y="3.6" DeltaX="4 4 4 4">透明文字</ofd:TextCode>\n'),
        _text(33, "OUTLINE", 0, 3.2, 3.5, 7, [2.1] * 7, "76 82 26 5",
              extra=' Fill="false" Stroke="true"',
              codes='        <ofd:StrokeColor Value="0 90 160"/>\n'
                    '        <ofd:TextCode X="0" Y="3.2" DeltaX="2.1 2.1 2.1 2.1 2.1 2.1 2.1">OUTLINE</ofd:TextCode>\n'),
        # ReadDirection 90 reads bottom-to-top; 180 reads right-to-left.
        _text(34, "B2UP", 0, 3.2, 3.2, 7, [2.0] * 4, "100 84 8 12",
              extra=' ReadDirection="90"',
              codes='        <ofd:TextCode X="0" Y="3.2" DeltaX="2 2 2 2">B2UP</ofd:TextCode>\n'),
        _text(35, "RTL180", 0, 3.2, 3, 7, [2.1] * 6, "140 84 30 6",
              extra=' ReadDirection="180"',
              codes='        <ofd:TextCode X="0" Y="3.2" DeltaX="2.1 2.1 2.1 2.1 2.1 2.1">RTL180</ofd:TextCode>\n'),
        # Vertical CJK run driven by DeltaY.
        _vertical(36, "竖排文字示例", "8 58 6 30", 4),
    ]

    shapes = """      <ofd:PathObject ID="40" Boundary="100 62 8 8" Fill="true" Stroke="false" Rule="Even-Odd">
        <ofd:FillColor Value="0 110 200"/>
        <ofd:AbbreviatedData>M 0 4 A 4 4 0 1 0 8 4 A 4 4 0 1 0 0 4 C S 2.6 4 A 1.4 1.4 0 1 1 5.4 4 A 1.4 1.4 0 1 1 2.6 4 C</ofd:AbbreviatedData>
      </ofd:PathObject>
      <ofd:PathObject ID="41" Boundary="112 62 16 8" DrawParam="3" Fill="false" Stroke="true">
        <ofd:AbbreviatedData>M 0 6 Q 4 0 8 6 Q 12 12 16 6</ofd:AbbreviatedData>
      </ofd:PathObject>
      <ofd:PathObject ID="42" Boundary="100 72 16 8" DrawParam="4" Fill="false" Stroke="true">
        <ofd:AbbreviatedData>M 0 4 B 4 8 8 0 12 4 B 13 0 15 8 16 4 C</ofd:AbbreviatedData>
      </ofd:PathObject>
      <ofd:PathObject ID="43" Boundary="120 72 8 8" DrawParam="5" Fill="false" Stroke="true">
        <ofd:AbbreviatedData>M 0 0 L 4 8 L 8 0</ofd:AbbreviatedData>
      </ofd:PathObject>
      <ofd:CompositeObject ID="44" Boundary="54 72 24 8" DrawParam="3">
        <ofd:PathObject ID="45" Boundary="0 0 24 8" Fill="true" Stroke="false">
          <ofd:FillColor Value="0 160 120" Alpha="90"/>
          <ofd:AbbreviatedData>M 0 0 L 24 0 L 24 8 L 0 8 C</ofd:AbbreviatedData>
        </ofd:PathObject>
        <ofd:TextObject ID="46" Boundary="2 1 20 6" Font="5" Size="4">
          <ofd:FillColor Value="0 90 70"/>
          <ofd:TextCode X="0" Y="4" DeltaX="4 4 4 4">嵌套组合</ofd:TextCode>
        </ofd:TextObject>
      </ofd:CompositeObject>
      <ofd:ImageObject ID="47" Boundary="88 62 10 10" ResourceID="10" ImageMask="true" Substitution="Auto"/>
"""

    return f"""<?xml version="1.0" encoding="UTF-8"?>
<ofd:Page xmlns:ofd="{NS}">
  <ofd:Area><ofd:PhysicalBox>0 0 150 100</ofd:PhysicalBox></ofd:Area>
  <ofd:Template TemplateID="1" ZOrder="Background"/>
  <ofd:Template TemplateID="3" ZOrder="Foreground"/>
  <ofd:Res BaseLoc="Res">
    <ofd:DrawParams>
      <ofd:DrawParam ID="6" LineWidth="0.25">
        <ofd:StrokeColor ColorSpace="1" Value="128"/>
      </ofd:DrawParam>
    </ofd:DrawParams>
  </ofd:Res>
  <ofd:Content>
    <ofd:Layer Type="Body">
      <ofd:ImageObject ID="90" CTM="20 0 0 20 0 0" Boundary="120 6 18 18" ResourceID="9"/>
      <ofd:ImageObject ID="91" CTM="12 0 0 12 0 0" Boundary="4 88 8 8" ResourceID="9"/>
{shapes}{"".join(parts)}    </ofd:Layer>
    <ofd:Layer Type="Foreground" DrawParam="6">
      <ofd:PathObject ID="92" Boundary="14 92 40 0.3" Fill="false" Stroke="true">
        <ofd:AbbreviatedData>M 0 0.15 L 40 0.15</ofd:AbbreviatedData>
      </ofd:PathObject>
    </ofd:Layer>
  </ofd:Content>
</ofd:Page>
"""


def page2_xml() -> str:
    shapes = """      <ofd:PathObject ID="60" Boundary="6 6 40 20" DrawParam="3" Fill="false" Stroke="true">
        <ofd:AbbreviatedData>M 0 18 B 8 0 32 0 40 18 Q 20 26 0 18 C</ofd:AbbreviatedData>
      </ofd:PathObject>
      <ofd:CompositeObject ID="61" Boundary="56 6 30 30" ResourceID="50"/>
"""
    parts = [
        _text(70, "第二页明细", 0, 5, 5, 5, [5, 5, 5, 5, 5], "6 32 40 7"),
        _text(71, "PAGE TWO", 0, 4.5, 3.5, 7, [2.1] * 8, "6 42 40 6"),
        # Vertical run on the right, rotated digits and slanted CJK.
        _vertical(72, "第二页竖排", "112 30 6 32", 4),
        _text(73, "270", 0, 3.2, 3.2, 7, [1.9] * 3, "88 32 20 5",
              extra=' ReadDirection="270"',
              codes='        <ofd:TextCode X="0" Y="3.2" DeltaX="1.9 1.9 1.9">270</ofd:TextCode>\n'),
        _text(74, "斜排文字", 0, 3.6, 4, 11, [4, 4, 4, 4], "20 50 40 6",
              extra=' CharDirection="45"'),
        # Two lines in one object: a second TextCode with its own Y.
        _text(75, "多行文字", 0, 3.6, 4, 5, [4, 4, 4, 4], "6 58 60 14",
              codes='        <ofd:TextCode X="0" Y="3.6" DeltaX="4 4 4 4">多行文字</ofd:TextCode>\n'
                    '        <ofd:TextCode X="0" Y="8.6" DeltaX="4 4 4 4 4">第二行文字</ofd:TextCode>\n'),
    ]
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<ofd:Page xmlns:ofd="{NS}">
  <ofd:Area><ofd:PhysicalBox>0 0 120 70</ofd:PhysicalBox></ofd:Area>
  <ofd:Content>
    <ofd:Layer Type="Body">
{shapes}{"".join(parts)}    </ofd:Layer>
  </ofd:Content>
</ofd:Page>
"""


def build(output: str = OUTPUT) -> str:
    os.makedirs(os.path.dirname(output), exist_ok=True)
    with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("OFD.xml", OFD_XML)
        archive.writestr("Doc_0/Document.xml", DOCUMENT_XML)
        archive.writestr("Doc_0/PublicRes.xml", PUBLIC_RES_XML)
        archive.writestr("Doc_0/DocumentRes.xml", DOCUMENT_RES_XML)
        archive.writestr("Doc_0/Tpls/Tpl_0/Content.xml", TEMPLATE_BACK_XML)
        archive.writestr("Doc_0/Tpls/Tpl_1/Content.xml", TEMPLATE_FRONT_XML)
        archive.writestr("Doc_0/Pages/Page_0/Content.xml", page1_xml())
        archive.writestr("Doc_0/Pages/Page_1/Content.xml", page2_xml())
        archive.writestr("Doc_0/Annots/Annot_0.xml", ANNOTS_INDEX_XML)
        archive.writestr("Doc_0/Annots/Content_0.xml", ANNOTS_PAGE0_XML)
        archive.writestr("Doc_0/Annots/Content_1.xml", ANNOTS_PAGE1_XML)
        archive.writestr("Doc_0/Attachs/Attachments.xml", ATTACHMENTS_XML)
        archive.writestr("Doc_0/Attachs/readme.txt",
                         "synthetic attachment for ofd2pdf tests\n")
        archive.writestr("Doc_0/Attachs/data.csv", "item,amount\npen,12.00\nbook,7.50\n")
        archive.writestr("Doc_0/Res/logo.png", _logo_png())
        archive.writestr("Doc_0/Res/stencil.png", _stencil_png())
    return output


if __name__ == "__main__":
    print("wrote", build())
